### ISSUE TITLE
"dashboard"

### ISSUE THREAD

**Issue by persianphilosopher** [tectiv3/standardfile#1]
Thanks for implementing this in go!
I followed the instructions and I am not sure if/what I am missing. Once the install is completed, whether I go to the ip:8888 or to the url via reverse proxy, I only see the word "Dashboard".  I wondered if that was all it takes but I can't use that as a server for standardnotes. Am I mistaken? Thank you again

**Comment by tectiv3** [comment]
I think you need to provide ip:8888/api url inside your app

**Comment by tectiv3** [comment]
And I have updated readme, nginx config specifically, cause now you need to pass some headers with every request.

**Comment by persianphilosopher** [comment]
Thank you!
It worked

**Comment by JeffAlyanak** [comment]
> 
> 
> Thank you!
> It worked

This should be added to the readme since it's otherwise very simple and straightforward.

**Comment by tectiv3** [comment]
it's [there](https://github.com/tectiv3/standardfile#you-may-require-to-add-api-to-the-url-of-your-server-if-you-plan-to-use-this-server-with-httpsstandardnotesorg) :)
