### ISSUE TITLE
Notes won't sync with server on armv7

### ISSUE THREAD

**Issue by GarrisonBaird** [tectiv3/standardfile#13]
```
Started StandardFile Server 0.3.2
Running on port 8888
Token is valid, claims:  &{[..uuid..] [...] { 0  1540571972  0 }}
Request: {[] [..sync_token..]  150}
Get items
loadItemsOlder
strconv.Atoi: parsing "1540572057139524600": value out of range
Save incoming items {[] [..sync_token..]  150}
Response: {
  "retrieved_items": [],
  "saved_items": [],
  "unsaved": [],
  "sync_token": "[..sync_token..]"
}
 202 [POST] "/api/items/sync" 85.895947ms 96
```
`standardfile_0.3.2_linux_arm7.tar.gz` on `Linux raspberrypi 4.14.50-v7`
Tested on latest Android, iOS and MacOS official clients. All notes will be downloaded after logging in, then they won't get synchronized anymore, just like it's always offline. Logs always repeats like this.

Everything works fine when using `standardfile_0.3.2_linux_64-bit.tar.gz`, there's no `strconv.Atoi: parsing "1540572057139524600": value out of range` in the log, I also can see new changes appear in the log.

**Comment by GarrisonBaird** [comment]
Probably an integer overflow on 32-bit system

**Comment by tectiv3** [comment]
Yeah.. Thanks. I'll look into it.

**Comment by tectiv3** [comment]
@GarrisonBaird should be fixed in latest release =)
