### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by cyberb** [tectiv3/standardfile#14]
I would like to this implementation of standard files to https://github.com/syncloud/platform as part of Standard Notes app.

Many apps already use LDAP as an authentication source.

Do you have plans to add some LDAP authentication logic?

**Comment by tectiv3** [comment]
This is just an implementation of https://standardfile.org/ protocol, if LDAP will be added to the specification - then yeah, I will implement it.

**Comment by cyberb** [comment]
Looks like there are two rest endpoints:

POST auth
POST auth/sign_in

Is it open for anyone to register?

Also it does not really say how implementor should store credentials.

**Comment by tectiv3** [comment]
Yes, but also `GET auth/params` which will be called first.

Yeah, if registration is not disabled via flag - anyone can register.

**Comment by cyberb** [comment]
So in theory it is posible to disable registration and use ldap for sign_in?
I guess it is up to implementor to decide what credential store to use.

If you are open for PRs I can look at it as I did similar thing for Syncthing recently: https://github.com/syncthing/syncthing/pull/5169

**Comment by tectiv3** [comment]
yeah, sure!

**Comment by cyberb** [comment]
Do you have any config file?

**Comment by tectiv3** [comment]
nope, but as number of options grow might as well add one.

**Comment by cyberb** [comment]
After checking how protocol works it appears that you are right. Spec says only part of the passowrd should be sent to the server. I guess they wanted users to be completely independent from the server.

So probably LDAP does not make sense at the moment.
