### ISSUE TITLE
listen on unix socket

### ISSUE THREAD

**Issue by cyberb** [tectiv3/standardfile#17]
Could you add an option to listen on unix socket file?
Very usefull when running behind a reverse proxy on the same box.

**Comment by JadeVane** [comment]
Any idea about how nginx connect to standardfile with socket mode?

**Comment by tectiv3** [comment]
Something like that:
`standardfile --socket /var/run/sf.sock`

```
proxy_pass http://unix:/var/run/sf.sock:/;
```

**Comment by JadeVane** [comment]
@tectiv3 BTW, run with nginx permissions, or you will get 502 status due to permission denied.
