### ISSUE TITLE
Installing Standard File server on Raspberry Pi

### ISSUE THREAD

**Issue by chegeiser** [tectiv3/standardfile#18]
I got this Go implementation up and running on a Raspberry Pi. So far it's running well with sync to iOS app, desktop app and webapp all working. I have a detailed writeup posted here: https://github.com/standardfile/ruby-server/issues/84

Maybe this will help someone else with setup. ;-)

**Comment by tectiv3** [comment]
I would recommend to switch apache for nginx or even caddy cause they are lighter on resources and your raspi will appreciate it :)
