### ISSUE TITLE
auth/params endpoint not returning correct value from iOS app

### ISSUE THREAD

**Issue by atmoio** [tectiv3/standardfile#2]
If I register with an account using the web app, and then try to sign in on iOS, it doesn't work. Upon a deeper inspection, the server is returning a different value for pw_salt depending on if I'm on web or iOS.

Most likely it's an email encoding issue. Are you able to check how your server is interpreting the email param when coming from an iOS app?

**Comment by tectiv3** [comment]
ok, I'll check. I wander why it regressed cause I was using it with web and ios clients just fine.

**Comment by rickt** [comment]
there is definitely something broken in the current version with regard to salt/passwords. however i don't think its *just* related to the iOS app. when i bring up the standardfile server and register a new account using the web app, it of course creates the user and logs me in as expected. however i am then unable to subsequently login via web (in an incognito window or after removing cookies etc) or via iOS app. 

i have spent some time following the code flow and trying to figure this out. what i do know is that the password string being passed to loadByEmailAndPassword() during web app or iOS app login does not match what is being stored in sqlite when that user is created. i have not dealt with salts/nonces/hashes in my golang work before so i have a bit of a learning curve to try and troubleshoot this, but i am trying! :)

unfortunately it is a showstopping bug for anyone trying to use the golang standardfile server as-is :-\

i will continue my poking around tonight and tomorrow and will update when i have found more details.

**Comment by tectiv3** [comment]
@rickt please check it against latest version.
This update requires migrations to be run.

Just `standardfile --migrate` before starting server. Or delete database file if it's empty.

**Comment by rickt** [comment]
@tectiv3 checked and works like a champ! i did not use --migrate as i had not yet used successfully on my own server. imported from previous web-based backup and all is well.

THANK YOU!!! 👍
