### ISSUE TITLE
Routing doesn't seem to work

### ISSUE THREAD

**Issue by nicolasbadia** [tectiv3/standardfile#4]
The command `curl http://localhost:8888/` return:

> Dashboard

but `curl http://localhost:8888/api` return:

> Not Found

Any idea of what is going on?
Also I tried to use `standardfile -debug` but I didn't manage to get the output...

**Comment by tectiv3** [comment]
There is no such route as `/api`
the only other `GET` route available is `auth/params`:
`$ curl http://localhost:8888/api/auth/params`
```json
{"errors":["Empty email"]}
```
