### ISSUE TITLE
failure to register

### ISSUE THREAD

**Issue by mock** [tectiv3/standardfile#6]
i was trying to register with the latest code for the server as of today and see this in the standardfiles server log when make the attempt:

```
==> log <==
2018/02/08 15:32:33 Unable to register
2018/02/08 15:32:33  422 [POST] "/api/auth" 319.049µs 33
```

have the nginx config file matching the one in the README, i have an ssl cert via letsencrypt with all the keys, and i am using the `/api` on the end of my custom domain name.

am i missing something?

**Comment by atmoio** [comment]
A user reported a similar issue on Slack and mentioned his solution was that he forgot to put "http://" before the domain when signing in.

**Comment by tectiv3** [comment]
`Unable to register` returned only in case account already exists.
